server:
  port: 7075
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login_management
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    maximum-pool-size: 20   # Increase pool size for better handling of concurrent requests
    minimum-idle: 10         # Set the minimum idle connections to avoid reconnecting often
    idle-timeout: 30000      # Idle connections timeout (in milliseconds)
    max-lifetime: 600000     # Maximum lifetime of a connection before it is closed and replaced
    connection-timeout: 30000  # Connection timeout in milliseconds
    pool-name: HikariCP

  redis:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: satishkalyankar06@gmail.com
    password: zgms ajog fovw rjbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework:web: DEBUG

jwt:
  secret: bG9jYWwtZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS0yNTYtYml0cy1sb25n
  expiration: 1209600000


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
